name: java spotless
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  java_spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: spotless
        run: mvn -B spotless:check
